# Site settings
title: Зароботок на слотах и в покере
email: eastfest@eastfest.com
description: Бешаные деньги со слотов онлайн казино, учимся зарабатывать в онлайн казино без напряга
baseurl: "/"
url: "http://krasnozerskaya-nov.ru"

author:
  name     : 'PokerMaster'
  email    : PokerMaster@krasnozerskaya-nov.ru
  url      : http://eastfest.github.io


github: https:/eastfest.github.io
disqus_shortname: "eastfest"

paginate: 3
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass
  
plugins: 
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives
  
# Build settings
markdown  : kramdown
permalink : /:title/
